---
- name: This play provisions k8s VMs based on intial config
  hosts: vm_host
  vars_files:
    - lab_vars.yml
  tasks:
    - name: Ensure cluster VMs are removed
      community.general.terraform:
        complex_vars: true
        project_path: "{{ playbook_dir }}/terraform"
        force_init: true
        variables:
          satellite_instance_cloud_image: "{{ rhel8_image_path }}"
          rhel8_instance_cloud_image: "{{ rhel8_image_path }}"
          rhel9_instance_cloud_image: "{{ rhel9_image_path }}"
          network_domain: "{{ lab_domain | default('demo.labs', true) }}"
          network_cidr: '{{ lab_network | default("192.168.254.0/24", true) | split(",") }}'
        state: absent

    - name: Remove resolved configuration
      become: true
      ansible.builtin.file:
        path: "/etc/systemd/resolved.conf.d/{{ lab_domain }}.conf"
        state: absent
